**SOLVING MURDER MYSTERY USING SQL WITH PYTHON !**

Installing db-sqlite3

In [69]:
pip install db-sqlite3

Importing required library

In [70]:
import pandas as pd
import sqlite3 as sql

Setting connection to the database

In [71]:
con = sql.connect('sql-murder-mystery.db')

1.  **Retrieve Crime Scene Report**:

Task: Run a query to retrieve the crime scene report for the murder that occurred on Jan.15, 2018, in SQL City. Gather all available details from the report.


In [93]:
display = '''SELECT *
FROM crime_scene_report
WHERE city = "SQL City"'''
pd.read_sql_query(display,con)

date     type                                        description  \
0  20180215   murder                         REDACTED REDACTED REDACTED   
1  20180215   murder  Someone killed the guard! He took an arrow to ...   
2  20170712    theft  A lone hunter stalks the night, firing arrows ...   
3  20170820    arson  Wield the Hammer of Sol with honor, Titan, it ...   
4  20171110  robbery  The Gjallarhorn shoulder-mounted rocket system...   
5  20180103  bribery  Apparently, Cayde thought it necessary to expo...   
6  20180115  assault  Hamilton: Lee, do you yield? Burr: You shot hi...   
7  20180115  assault                                   Report Not Found   
8  20180115   murder  Security footage shows that there were 2 witne...   

       city  
0  SQL City  
1  SQL City  
2  SQL City  
3  SQL City  
4  SQL City  
5  SQL City  
6  SQL City  
7  SQL City  
8  SQL City

In [94]:
query1 = '''SELECT *
FROM crime_scene_report
WHERE city = "SQL City" and
type="murder" and date="20180115"'''
pd.read_sql_query(query1,con)

date    type                                        description  \
0  20180115  murder  Security footage shows that there were 2 witne...   

       city  
0  SQL City

Point to be noted: Security footage shows that there were 2 witnesses.

 The first witness lives at the last house on \"Northwestern Dr\". The second witness, named Annabel, lives somewhere on \"Franklin Ave\".','SQL City'

2. **Witness Personal Details:**
Task: Check the personal details of witnesses involved in the case. Retrieve their names, addresses, and any other relevant information.


In [76]:
display1 = pd.read_sql_query(
'''SELECT *
FROM person''',con)

In [77]:
display1

id                 name  license_id  address_number  \
0      10000   Christoper Peteuil      993845             624   
1      10007  Kourtney Calderwood      861794            2791   
2      10010            Muoi Cary      385336             741   
3      10016          Era Moselle      431897            1987   
4      10025         Trena Hornby      550890             276   
...      ...                  ...         ...             ...   
10006  99936          Luba Benser      274427             680   
10007  99941      Roxana Mckimley      975942            1613   
10008  99965      Cherie Zeimantz      287627            3661   
10009  99982          Allen Cruse      251350            3126   
10010  99990         Vance Hunten      830407            3056   

      address_street_name        ssn  
0            Bankhall Ave  747714076  
1           Gustavus Blvd  477972044  
2         Northwestern Dr  828638512  
3           Wood Glade St  614621061  
4           Daws Hill Way  223877684  
...                   ...        ...  
10006        Carnage Blvd  685095054  
10007             Gate St  512136801  
10008       The Water Ave  362877324  
10009           N Jean Dr  348734531  
10010       Lancefield St  896677562  

[10011 rows x 6 columns]

In [78]:
query2=pd.read_sql_query(
'''SELECT *
FROM person WHERE address_street_name="Northwestern Dr" ORDER BY address_number limit 1''',con)


In [79]:
query2

id             name  license_id  address_number address_street_name  \
0  89906  Kinsey Erickson      510019             309     Northwestern Dr   

         ssn  
0  635287661

In [80]:
query_2=pd.read_sql_query(
'''SELECT *
FROM person WHERE address_street_name="Franklin Ave" and name LIKE "%Annabel%" ''',con)

In [81]:
query_2

id            name  license_id  address_number address_street_name  \
0  16371  Annabel Miller      490173             103        Franklin Ave   

         ssn  
0  318771143

3. **View Witness Interviews:**
Task: Access the recorded interviews of witnesses conducted after the murder. Gather insights into their statements and potential clues.


In [82]:
query3=pd.read_sql_query(
'''SELECT *
FROM interview ''',con)
query3

person_id                                         transcript
0         28508                ‘I deny it!’ said the March Hare.\n
1         63713                                                 \n
2         86208      way, and the whole party swam to the shore.\n
3         35267  lessons in here? Why, there’s hardly room for ...
4         33856                                                 \n
...         ...                                                ...
4986      37357  Alice did not wish to offend the Dormouse agai...
4987      10206  time,’ she said, ‘than waste it in asking ridd...
4988      14887  I heard a gunshot and then saw a man run out. ...
4989      16371  I saw the murder happen, and I recognized the ...
4990      67318  I was hired by a woman with a lot of money. I ...

[4991 rows x 2 columns]

In [83]:
query3=pd.read_sql_query(
'''SELECT *
FROM interview where person_id = "16371"''',con)
query3

person_id                                         transcript
0      16371  I saw the murder happen, and I recognized the ...

Witness 1- I heard a gunshot and then saw a man run out. He had a "Get Fit Now Gym" bag. The membership number on the bag started with "48Z". Only gold members have those bags. The man got into a car with a plate that included "H42W".

Witness 2- I saw the murder happen, and I recognized the killer from my gym when I was working out last week on January the 9th

In [84]:
query_3=pd.read_sql_query('''SELECT *
FROM interview
WHERE person_id = '14887';''',con)
query_3

person_id                                         transcript
0      14887  I heard a gunshot and then saw a man run out. ...

4. **Check Gym Database**:
Task: Investigate the gym database using details obtained from the crime scene report and witness interviews. Look for any gym-related information that might be relevant.


In [85]:
pd.read_sql_query('''SELECT *
FROM get_fit_now_check_in''',con)

membership_id  check_in_date  check_in_time  check_out_time
0            NL318       20180212            329             365
1            NL318       20170811            469             920
2            NL318       20180429            506             554
3            NL318       20180128            124             759
4            NL318       20171027            418            1019
...            ...            ...            ...             ...
2698         4KB72       20170422           1016            1114
2699         4KB72       20170630            408             885
2700         48Z7A       20180109           1600            1730
2701         48Z55       20180109           1530            1700
2702         90081       20180109           1600            1700

[2703 rows x 4 columns]

From witness 1 we came to know that membership number on the murderer's bag started with "48Z". Only gold members have those bags. The man got into a car with a plate that included "H42W".

from Witness 2 we came to know that he found the killer last week on January the 9th

In [95]:
query4=pd.read_sql_query(
'''SELECT *
FROM get_fit_now_check_in
WHERE check_in_date = '20180109'
AND membership_id LIKE '48Z%';''',con)
query4

membership_id  check_in_date  check_in_time  check_out_time
0         48Z7A       20180109           1600            1730
1         48Z55       20180109           1530            1700

5. **Check car details**

Task: Examine the car details associated with the crime scene. Retrieve information about the vehicles present during the incident.


Checking for the killer car using the given clue

In [97]:
query_4=pd.read_sql_query(
'''SELECT * from drivers_license WHERE plate_number LIKE '%H42W%' and gender = "male";''',con
)
query_4

id  age  height eye_color hair_color gender plate_number   car_make  \
0  423327   30      70     brown      brown   male       0H42W2  Chevrolet   
1  664760   21      71     black      black   male       4H42WR     Nissan   

  car_model  
0  Spark LS  
1    Altima

6. **Personal Details:**

Task: Identify and collect personal details mentioned in the previous query. This includes names, addresses, and any additional details.


In [96]:
query_5=pd.read_sql_query(
''' SELECT * from person where license_id="423327"''',con
)
query_5

id           name  license_id  address_number    address_street_name  \
0  67318  Jeremy Bowers      423327             530  Washington Pl, Apt 3A   

         ssn  
0  871539279

In [89]:
query5=pd.read_sql_query(
    ''' SELECT * from person where license_id="664760"''',con
)
query5

id            name  license_id  address_number address_street_name  \
0  51739  Tushar Chandra      664760             312              Phi St   

         ssn  
0  137882671

7. **Membership Status at the Gym:**
Task: Determine who is identified in the previous query as a member of the gym. Utilize the gym database to confirm their membership status.


In [90]:
query6=pd.read_sql_query(
    ''' SELECT * from get_fit_now_member WHERE membership_status="gold" AND id LIKE '48Z%';''',con
)
query6

id  person_id           name  membership_start_date membership_status
0  48Z7A      28819   Joe Germuska               20160305              gold
1  48Z55      67318  Jeremy Bowers               20160101              gold

8. **Analyze and Draw Conclusions:**

Task: Analyze the collected data, including crime scene reports, witness interviews, gym records, and car details. Draw conclusions or hypotheses based on the information available.


In [91]:
query_8 = '''
SELECT *
FROM get_fit_now_member
WHERE person_id = "51739" OR person_id = "67318";'''
pd.read_sql_query(query_8,con)

id  person_id           name  membership_start_date membership_status
0  48Z55      67318  Jeremy Bowers               20160101              gold

**The conclusion we get is Jeremy Bowers is the killer/murderer**

In [92]:
query_9 = '''
SELECT *
FROM interview
WHERE person_id = 67318;
'''
pd.read_sql_query(query_9, con)

person_id                                         transcript
0      67318  I was hired by a woman with a lot of money. I ...

9. **Document Findings:**

Task: Document your findings and any insights gained from the SQL investigation. Summarize the key details that lead you to your conclusions.


Findings Summary:

- Witnesses, including Annabel and Morty Schapiro, provided crucial information.
- Jeremy Bowers emerged as the prime suspect based on evidence linking him to the crime scene.
- Vehicle details and gym membership records corroborated Bowers' involvement.
- Critical analysis of witness testimonies and data integration led to a confident conclusion implicating Jeremy Bowers as the perpetrator.

10. **Prepare a Report:**

Task: Prepare a detailed report for the detective, summarizing the events, suspects, and your conclusions. Present the evidence and rationale behind your findings.

1. Crime Scene Report:

Date: January 15, 2018

Type: Murder

City: SQL City

Description: Security footage indicates two witnesses.




2. Witnesses:

a) One of the witnesses, Annabel, resides at the final house located on "Northwestern Dr".

b) The other witness, named Annabel, is a resident of "Franklin Ave".

3. Witness Testimonies:

a) Annabel reported seeing the suspect, whom she identified as the murderer, at her gym on January 9, 2018.

b) Morty Schapiro, the second witness, provided crucial details:

i) He witnessed a man fleeing the scene after hearing a gunshot.
ii) The fleeing individual was carrying a gym bag from the "Get Fit Now Gym".
iii) The membership number on the gym bag started with "48Z", indicating the individual was a gold member.
iv) The man escaped in a vehicle with a license plate containing the characters "H42W".

3. Car Details:

After obtaining information about the vehicle associated with the license plate "H42W", it was revealed that three individuals (one female and two males) were linked to vehicles with matching plates:

a) Suspect 1: Jeremy Bowers, identified by ID 67318.

b) Suspect 2: Tushar Chandra, identified by ID 51739.

4. Gym Membership:

Investigation into the gym's membership records disclosed that there were two individuals with "Gold Membership" status and gym bags marked with "48Z" initials:
a) Suspect 1: Joe Germuska.

b) Suspect 2: Jeremy Bowers, who matched the description provided by the witnesses.

Conclusion:

Based on the comprehensive analysis, it has been conclusively determined that the perpetrator of the crime is Jeremy Bowers. He was identified as a gold member of the gym, possessing a gym bag marked "48Z55", and was observed committing the murder on January 15, 2018. Jeremy subsequently fled the scene using his vehicle, which bore the license plate "0H42W2".




11. **Reflect on the Investigation:**

Task: Reflect on the investigative process. What challenges did you encounter, and how did you overcome them? Share your reflections on the case-solving experience.


Ans: The investigation was tricky because we had to listen carefully to what the witnesses said and make sense of it. We also had to find out who owned a certain car and check gym records to see who could be the suspect. By working together and applying critical thinking to analyze the evidence, we figured out that Jeremy Bowers was the one who committed the crime. It taught us that solving mysteries takes patience and critical thinking

**Jeremy Bowers is the KILLER!!**